# -*- coding: utf-8 -*-
"""streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyvP0arQI4_1JYLzyiT9-ycOE_rWYIS5
"""

print("Hello World")